using System;
using System.Runtime.InteropServices;

namespace MainDen.Windows.API
{
    // Types | Constants
    public static partial class Keyboard
    {
        public static class LayoutHandle
        {
            public static readonly IntPtr Previous = (IntPtr)0;
            public static readonly IntPtr Next = (IntPtr)1;
        }
        [Flags]
        public enum EventFlags
        {
            ExtendedKey = 0x0001,
            KeyUp = 0x0002,
        }
        [Flags]
        public enum LayoutFlags : uint
        {
            Activate = 0x00000001,
            SubstitudeOk = 0x00000002,
            Reorder = 0x00000008,
            ReplaceLang = 0x00000010,
            NoteLLShell = 0x00000080,
            SetForProcess = 0x00000100,
            ShiftLock = 0x00010000,
            Reset = 0x40000000
        }
        [Flags]
        public enum KeyModifiers : int
        {
            None = 0,
            Alt = 1,
            Control = 2,
            Shift = 4,
            Windows = 8
        }
        public enum LanguageIdentifier : uint
        {
            SystemDefault = 0x0800,
            UserDefault = 0x0400,
            Belarusian = 0x0423,
            Chinese = 0x0C04,
            Franch = 0x080C,
            German = 0x0C07,
            Japanese = 0x0411,
            Kazak = 0x043F,
            Russian = 0x0419,
            Ukrainian = 0x0422,
            USEnglish = 0x0409
        }
        public enum VirtualKeyStates : int
        {
            Modifiers = -65536,
            None = 0,
            LButton = 1,
            RButton = 2,
            Cancel = 3,
            MButton = 4,
            XButton1 = 5,
            XButton2 = 6,
            Back = 8,
            Tab = 9,
            LineFeed = 10,
            Clear = 12,
            Return = 13,
            Enter = 13,
            Shift = 16,
            Control = 17,
            Ctrl = 17,
            Alt = 18,
            Menu = 18,
            Pause = 19,
            CapsLock = 20,
            Capital = 20,
            Kana = 21,
            KanaMode = 21,
            Hanguel = 21,
            ImeHanguel = 21,
            ImeKana = 21,
            HanguelMode = 21,
            Hangul = 21,
            ImeHangul = 21,
            HangulMode = 21,
            ImeOn = 22,
            Junja = 23,
            ImeJunja = 23,
            JunjaMode = 23,
            ImeFinal = 24,
            Final = 24,
            FinalMode = 24,
            Hanja = 25,
            ImeHanja = 25,
            HanjaMode = 25,
            Kanji = 25,
            KanjiMode = 25,
            ImeKanji = 25,
            ImeOff = 26,
            Escape = 27,
            ImeConvert = 28,
            ImeNonConvert = 29,
            ImeAceept = 30,
            ImeModeChange = 31,
            Space = 32,
            Prior = 33,
            PageUp = 33,
            PageDown = 34,
            End = 35,
            Next = 34,
            Home = 36,
            Left = 37,
            Up = 38,
            Right = 39,
            Down = 40,
            Select = 41,
            Print = 42,
            Execute = 43,
            Snapshot = 44,
            PrintScreen = 44,
            Insert = 45,
            Delete = 46,
            Help = 47,
            D0 = 48,
            D1 = 49,
            D2 = 50,
            D3 = 51,
            D4 = 52,
            D5 = 53,
            D6 = 54,
            D7 = 55,
            D8 = 56,
            D9 = 57,
            A = 65,
            B = 66,
            C = 67,
            D = 68,
            E = 69,
            F = 70,
            G = 71,
            H = 72,
            I = 73,
            J = 74,
            K = 75,
            L = 76,
            M = 77,
            N = 78,
            O = 79,
            P = 80,
            Q = 81,
            R = 82,
            S = 83,
            T = 84,
            U = 85,
            V = 86,
            W = 87,
            X = 88,
            Y = 89,
            Z = 90,
            LeftWin = 91,
            LWin = 91,
            RightWin = 92,
            RWin = 92,
            Apps = 93,
            Sleep = 95,
            NumPad0 = 96,
            NumPad1 = 97,
            NumPad2 = 98,
            NumPad3 = 99,
            NumPad4 = 100,
            NumPad5 = 101,
            NumPad6 = 102,
            NumPad7 = 103,
            NumPad8 = 104,
            NumPad9 = 105,
            Multiply = 106,
            Add = 107,
            Separator = 108,
            Subtract = 109,
            Decimal = 110,
            Divide = 111,
            F1 = 112,
            F2 = 113,
            F3 = 114,
            F4 = 115,
            F5 = 116,
            F6 = 117,
            F7 = 118,
            F8 = 119,
            F9 = 120,
            F10 = 121,
            F11 = 122,
            F12 = 123,
            F13 = 124,
            F14 = 125,
            F15 = 126,
            F16 = 127,
            F17 = 128,
            F18 = 129,
            F19 = 130,
            F20 = 131,
            F21 = 132,
            F22 = 133,
            F23 = 134,
            F24 = 135,
            NumLock = 144,
            ScrollLock = 145,
            Scroll = 145,
            ImeProcessed = 155,
            LShift = 160,
            LeftShift = 160,
            RightShift = 161,
            RShift = 161,
            LeftCtrl = 162,
            LControl = 162,
            LeftControl = 162,
            LCtrl = 162,
            RightCtrl = 163,
            RControl = 163,
            RightControl = 163,
            RCtrl = 163,
            LeftAlt = 164,
            LMenu = 164,
            LeftMenu = 164,
            LAlt = 164,
            RightAlt = 165,
            RMenu = 165,
            RAlt = 165,
            RightMenu = 165,
            BrowserBack = 166,
            BrowserForward = 167,
            BrowserRefresh = 168,
            BrowserStop = 169,
            BrowserSearch = 170,
            BrowserFavorites = 171,
            BrowserHome = 172,
            VolumeMute = 173,
            VolumeDown = 174,
            VolumeUp = 175,
            MediaNextTrack = 176,
            MediaPreviousTrack = 177,
            MediaStop = 178,
            MediaPlayPause = 179,
            LaunchMail = 180,
            LaunchMediaSelect = 181,
            LaunchApplication1 = 182,
            LaunchApplication2 = 183,
            Oem1 = 186,
            OemSemicolon = 186,
            OemСolon = 186,
            OemPlus = 187,
            OemComma = 188,
            OemMinus = 189,
            OemPeriod = 190,
            OemDot = 190,
            Oem2 = 191,
            OemSlash = 191,
            OemQuestion = 191,
            OemBackquote = 192,
            OemBacktick = 192,
            Oem3 = 192,
            OemGrave = 192,
            OemTilde = 192,
            Oem4 = 219,
            OemOpenBracket = 219,
            OemLeftBracket = 219,
            OemOpenSquareBracket = 219,
            OemLeftSquareBracket = 219,
            OemOpenBrace = 219,
            OemLeftBrace = 219,
            OemOpenCurlyBracket = 219,
            OemLeftCurlyBracket = 219,
            OemBackslash = 220,
            OemVerticalBar = 220,
            OemPipeline = 220,
            OemPipe = 220,
            Oem5 = 220,
            OemCloseBracket = 221,
            OemRightBracket = 221,
            OemCloseSquareBracket = 221,
            Oem6 = 221,
            OemRightSquareBracket = 221,
            OemCloseBrace = 221,
            OemRightBrace = 221,
            OemCloseCurlyBracket = 221,
            OemRightCurlyBracket = 221,
            OemQuote = 222,
            OemSingleQuote = 222,
            Oem7 = 222,
            OemDoubleQuote = 222,
            Oem8 = 223,
            Oem102 = 226,
            ImeProcess = 229,
            Packet = 231,
            Attn = 246,
            CrSel = 247,
            ExSel = 248,
            EraseEof = 249,
            Play = 250,
            Zoom = 251,
            NoName = 252,
            PA1 = 253,
            OemClear = 254,
            KeyCode = 65535,
            ShiftModifier = 65536,
            ControlModifier = 131072,
            AltModifier = 262144,
        }
    }
    // Methods
    public static partial class Keyboard
    {
        [DllImport("user32.dll", SetLastError = true)]
        public static extern IntPtr ActivateKeyboardLayout(IntPtr hKL, LayoutFlags Flags);
        [DllImport("user32.dll", SetLastError = true)]
        public static extern short GetAsyncKeyState(VirtualKeyStates vKey);
        [DllImport("user32.dll")]
        public static extern IntPtr GetKeyboardLayout(uint threadId);
        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool GetKeyboardState(byte[] lpKeyState);
        [DllImport("USER32.dll")]
        public static extern short GetKeyState(VirtualKeyStates nVirtKey);
        [DllImport("user32.dll")]
        public static extern void keybd_event(byte bVk, byte bScan, EventFlags dwFlags, UIntPtr dwExtraInfo);
        [DllImport("user32.dll", SetLastError = true)]
        public static extern IntPtr LoadKeyboardLayout(string pwszKLId, LayoutFlags Flags);
        [DllImport("user32.dll", SetLastError = true)]
        public static extern bool UnloadKeyboardLayout(IntPtr hKL);
    }
}
